name: Update

on:
  push:

jobs:
  update:
    if: contains(github.event.commits[0].message, '[generated]') == false
    name: Update conformance folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Cleanup files
        run: cargo run --release clean

      - name: Update
        run: cargo run --release

      - name: Publish changes to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git add -A
          git commit -m "[actions] generated conformance tests"
          git push https://:${{ secrets.GITHUB_TOKEN }}@github.com/memothelemo-archive/ts-conformance-gen.git HEAD:master
