name: Update

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    if: contains(github.event.commits[0].message, '[generated]') == false
    name: Update conformance folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Update
        run: cargo run --release
